INSERT INTO company_registry_entries (
    enterprise_number,
    name,
    legal_form,
    status,
    address,
    postal_code,
    city,
    nace_code,
    activity_label,
    active,
    source,
    created_at,
    updated_at
) VALUES
    (
        'BE 1029.610.755',
        'PROFACILE',
        'SRL',
        'ACTIF',
        'Avenue Marius Renard 37',
        '1070',
        'Anderlecht',
        NULL,
        'Services informatiques',
        true,
        'BCE Open Data local',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'BE 0742.742.361',
        'FOVU DE BAHAM',
        'SRL',
        'ACTIF',
        'Chaussee de Mons 181',
        '1070',
        'Anderlecht',
        NULL,
        NULL,
        true,
        'BCE Open Data local',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'BE 0671.509.224',
        'MOTIOBEL',
        NULL,
        'ACTIF',
        'Rue Neuve Mettez 294',
        '6717',
        'Attert',
        NULL,
        NULL,
        true,
        'BCE Open Data local',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    )
ON CONFLICT (enterprise_number) DO UPDATE SET
    name = EXCLUDED.name,
    legal_form = EXCLUDED.legal_form,
    status = EXCLUDED.status,
    address = EXCLUDED.address,
    postal_code = EXCLUDED.postal_code,
    city = EXCLUDED.city,
    nace_code = EXCLUDED.nace_code,
    activity_label = EXCLUDED.activity_label,
    active = EXCLUDED.active,
    source = EXCLUDED.source,
    updated_at = CURRENT_TIMESTAMP;
